# Generated by Django 4.2.1 on 2023-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndustrialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.IntegerField()),
                ("intensity", models.IntegerField()),
                ("sector", models.CharField(max_length=20)),
                ("topic", models.CharField(max_length=20)),
                ("insight", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=20)),
                ("start_year", models.IntegerField()),
                ("impact", models.IntegerField()),
                ("added", models.CharField(max_length=100)),
                ("published", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("relevance", models.IntegerField()),
                ("pestle", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("likelihood", models.IntegerField()),
            ],
        ),
    ]
