# Generated by Django 4.2.1 on 2023-05-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_industrialdata_end_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrialdata",
            name="impact",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="industrialdata",
            name="intensity",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="industrialdata",
            name="likelihood",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="industrialdata",
            name="relevance",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="industrialdata",
            name="start_year",
            field=models.CharField(max_length=100),
        ),
    ]
